# This file was generated by GoReleaser. DO NOT EDIT.
cask "pcpm" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "ff5ef7149a6a10a719f6619ea547f0bacd1f042a55114edf9eabe0209d437523"
      url "https://github.com/xunull/pcpm/releases/download/v#{version}/pcpm_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/xunull/pcpm"
    end
    on_arm do
      sha256 "19bee25794b12af861d7074a21e40b9def2824173788c93690c97a4c88ed09d0"
      url "https://github.com/xunull/pcpm/releases/download/v#{version}/pcpm_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/xunull/pcpm"
    end
  end

  on_linux do
    on_intel do
      sha256 "02a05653ff88ff0e984fd26f4497fb120b2ba86cc20f0e86271aea36e4c42088"
      url "https://github.com/xunull/pcpm/releases/download/v#{version}/pcpm_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/xunull/pcpm"
    end
    on_arm do
      sha256 "7f61827c3d9b92d03028d40e85afe4cc30afbe27b6c00fb4c175bfb05c046c7b"
      url "https://github.com/xunull/pcpm/releases/download/v#{version}/pcpm_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/xunull/pcpm"
    end
  end

  name "pcpm"
  desc "Find processes whose launching job is gone — a dev server an agent started and never stopped"
  homepage "https://github.com/xunull/pcpm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pcpm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pcpm"]
    end
  end

  # No zap stanza required

end
