# This file was generated by GoReleaser. DO NOT EDIT.
cask "pcpm" do
  version "0.1.6"

  on_macos do
    on_intel do
      sha256 "0c2f026da49b6c71641519d8511662a331c838754d7977b4b6edfe3b3c319e84"
      url "https://github.com/xunull/pcpm/releases/download/v#{version}/pcpm_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/xunull/pcpm"
    end
    on_arm do
      sha256 "428c71a84d2e665a091e0d58aa81cb2e119b7552aee0b7730a5f8f16d7beb1ba"
      url "https://github.com/xunull/pcpm/releases/download/v#{version}/pcpm_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/xunull/pcpm"
    end
  end

  on_linux do
    on_intel do
      sha256 "34eded7adab5c996774f597d3a5e32f02c44855f044b96b7244868e32aa607f7"
      url "https://github.com/xunull/pcpm/releases/download/v#{version}/pcpm_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/xunull/pcpm"
    end
    on_arm do
      sha256 "e1f2c4649740148ff6c361ce8dc3456a01d15e236c5844c29d387e7f3c9f97fa"
      url "https://github.com/xunull/pcpm/releases/download/v#{version}/pcpm_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/xunull/pcpm"
    end
  end

  name "pcpm"
  desc "Find processes whose launching job is gone — a dev server an agent started and never stopped"
  homepage "https://github.com/xunull/pcpm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pcpm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pcpm"]
    end
  end

  # No zap stanza required

end
