# This file was generated by GoReleaser. DO NOT EDIT.
cask "pcpm" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "bf76a272c1800d74ff68709c7f566dc13e8b75e969627e1999a5e5b0760ef89f"
      url "https://github.com/xunull/pcpm/releases/download/v#{version}/pcpm_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/xunull/pcpm"
    end
    on_arm do
      sha256 "860f9ff3989948e16e1fb13b274cdd00bb07c3ffb3e3c1d1896e773ce3894f5c"
      url "https://github.com/xunull/pcpm/releases/download/v#{version}/pcpm_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/xunull/pcpm"
    end
  end

  on_linux do
    on_intel do
      sha256 "9ec207644552c2abd7bb8572e878d7e64f40baa09566dde5473728eca4d0e2eb"
      url "https://github.com/xunull/pcpm/releases/download/v#{version}/pcpm_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/xunull/pcpm"
    end
    on_arm do
      sha256 "3f74de60d91e5a55f5e01c2f00ec53474fa6c493156aa09ce93716a67ab12814"
      url "https://github.com/xunull/pcpm/releases/download/v#{version}/pcpm_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/xunull/pcpm"
    end
  end

  name "pcpm"
  desc "Find processes whose launching job is gone — a dev server an agent started and never stopped"
  homepage "https://github.com/xunull/pcpm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pcpm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pcpm"]
    end
  end

  # No zap stanza required

end
